services:
  hive:
    image: apache/hive
    ports:
    - 10000:10000
    - 10002:10002
    environment:
      - SERVICE_NAME=HIVESERVER2
    

  imapala:
    image: apache/impala

  spark:
    image: spark
    command: /opt/spark/bin/spark-shell

  hadoop:
    image: apache/hadoop
    ports:
    - 9870:9870
    - 8088:8088

  flume:
    image: